/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  AmrutAachamen: () => import('#controllers/amrut_aachamen_controller'),
  Application: () => import('#controllers/application_controller'),
  DailyDarshans: () => import('#controllers/daily_darshans_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  Departments: () => import('#controllers/departments_controller'),
  Groups: () => import('#controllers/groups_controller'),
  Lessons: () => import('#controllers/lessons_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Overviews: () => import('#controllers/overviews_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Progresses: () => import('#controllers/progresses_controller'),
  Quotes: () => import('#controllers/quotes_controller'),
  Roles: () => import('#controllers/roles_controller'),
  Sections: () => import('#controllers/sections_controller'),
  Tasks: () => import('#controllers/tasks_controller'),
  Uploads: () => import('#controllers/uploads_controller'),
  Users: () => import('#controllers/users_controller'),
}
