/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: bigint | number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DailyDarshanSchema extends BaseModel {
  static $columns = ['createdAt', 'date', 'description', 'id', 'imageUrl', 'title', 'updatedAt'] as const
  $columns = DailyDarshanSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare date: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageUrl: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DepartmentSchema extends BaseModel {
  static $columns = ['createdAt', 'departmentHeadId', 'departmentId', 'departmentName', 'description', 'updatedAt'] as const
  $columns = DepartmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare departmentHeadId: bigint | number | null
  @column({ isPrimary: true })
  declare departmentId: number
  @column()
  declare departmentName: string
  @column()
  declare description: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GroupSchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'description', 'groupId', 'groupName', 'memberIds', 'updatedAt'] as const
  $columns = GroupSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare createdBy: bigint | number | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare groupId: number
  @column()
  declare groupName: string
  @column()
  declare memberIds: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LessonSchema extends BaseModel {
  static $columns = ['assignDepartmentId', 'assignGroupId', 'assignHeadOnly', 'assignScope', 'assignSectionId', 'assignStudentId', 'createdAt', 'createdBy', 'dateEnd', 'dateStart', 'departmentId', 'description', 'lessonId', 'lessonTitle', 'lessonType', 'mediaPublicId', 'mediaUrl', 'progressPoints', 'roleCode', 'updatedAt'] as const
  $columns = LessonSchema.$columns
  @column()
  declare assignDepartmentId: number | null
  @column()
  declare assignGroupId: number | null
  @column()
  declare assignHeadOnly: boolean | null
  @column()
  declare assignScope: string
  @column()
  declare assignSectionId: number | null
  @column()
  declare assignStudentId: bigint | number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare createdBy: bigint | number | null
  @column.date()
  declare dateEnd: DateTime
  @column.date()
  declare dateStart: DateTime
  @column()
  declare departmentId: number | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare lessonId: number
  @column()
  declare lessonTitle: string
  @column()
  declare lessonType: string
  @column()
  declare mediaPublicId: string | null
  @column()
  declare mediaUrl: string | null
  @column()
  declare progressPoints: number | null
  @column()
  declare roleCode: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ModuleSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'isActive', 'moduleCode', 'moduleId', 'name', 'updatedAt'] as const
  $columns = ModuleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare isActive: boolean | null
  @column()
  declare moduleCode: string
  @column({ isPrimary: true })
  declare moduleId: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NotificationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isRead', 'message', 'relatedId', 'targetRole', 'title', 'type'] as const
  $columns = NotificationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isRead: boolean
  @column()
  declare message: string
  @column()
  declare relatedId: number | null
  @column()
  declare targetRole: string | null
  @column()
  declare title: string
  @column()
  declare type: string
}

export class OverviewImageSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'publicId', 'section', 'title', 'url'] as const
  $columns = OverviewImageSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare publicId: string
  @column()
  declare section: string
  @column()
  declare title: string
  @column()
  declare url: string
}

export class QuoteSchema extends BaseModel {
  static $columns = ['addToHero', 'createdAt', 'description', 'displayEndDate', 'displayStartDate', 'eventDate', 'eventEndDate', 'eventStartDate', 'id', 'imageUrl', 'isApproved', 'name', 'publicId', 'status', 'title', 'type'] as const
  $columns = QuoteSchema.$columns
  @column()
  declare addToHero: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column.date()
  declare displayEndDate: DateTime | null
  @column.date()
  declare displayStartDate: DateTime | null
  @column.date()
  declare eventDate: DateTime
  @column.date()
  declare eventEndDate: DateTime | null
  @column.date()
  declare eventStartDate: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageUrl: string
  @column()
  declare isApproved: string | null
  @column()
  declare name: string
  @column()
  declare publicId: string
  @column()
  declare status: string | null
  @column()
  declare title: string
  @column()
  declare type: string
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'permissions', 'roleCode', 'roleName', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare permissions: any
  @column({ isPrimary: true })
  declare roleCode: string
  @column()
  declare roleName: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SectionSchema extends BaseModel {
  static $columns = ['createdAt', 'departmentId', 'description', 'name', 'sectionHeadId', 'sectionId', 'updatedAt'] as const
  $columns = SectionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare departmentId: number
  @column()
  declare description: string | null
  @column()
  declare name: string
  @column()
  declare sectionHeadId: bigint | number | null
  @column({ isPrimary: true })
  declare sectionId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TaskSchema extends BaseModel {
  static $columns = ['assignedBy', 'assignedTo', 'completedAt', 'createdAt', 'departmentId', 'description', 'dueDate', 'sectionId', 'status', 'taskId', 'title'] as const
  $columns = TaskSchema.$columns
  @column()
  declare assignedBy: number | null
  @column()
  declare assignedTo: number
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare departmentId: number | null
  @column()
  declare description: string | null
  @column.date()
  declare dueDate: DateTime | null
  @column()
  declare sectionId: number | null
  @column()
  declare status: string | null
  @column({ isPrimary: true })
  declare taskId: number
  @column()
  declare title: string
}

export class UserSchema extends BaseModel {
  static $columns = ['avatar', 'bod', 'createdAt', 'departmentId', 'joiningDate', 'name', 'password', 'roleCode', 'sectionId', 'standardId', 'status', 'suid', 'updatedAt', 'username'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatar: string | null
  @column.date()
  declare bod: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare departmentId: number | null
  @column.date()
  declare joiningDate: DateTime | null
  @column()
  declare name: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare roleCode: string
  @column()
  declare sectionId: number | null
  @column()
  declare standardId: number | null
  @column()
  declare status: string
  @column({ isPrimary: true })
  declare suid: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
}
